on:
	push:
name: action
jobs:
	hello-world:
		name: Un job para saludar
		runs-on: ubuntu-latest
		steps:
			- name: Step Hola Mundo
			  id: hello
			  uses: iecp/hello-world-docker-action@v1
			  with:
				who-to-greet: "Iecp"
			- name: Usar el output
			  run: echo "La fecha fue {{ steps.hello.outputs.time }}"
